### status
GET http://localhost:3000/api/status
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYWQxYThlNzJlN2M5MTY3MWM5ZGZjNyIsImlhdCI6MTY1NTUxMTg5OCwiZXhwIjoxNjU1NTk4Mjk4fQ.wC95-bEcm78uOkIVXmOxD6gakSRl8U-F0xrnwiOdWpo
###
### agendamento getAll
GET  http://localhost:3000/api/agendamento 
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYWQxYThlNzJlN2M5MTY3MWM5ZGZjNyIsImlhdCI6MTY1NTUxMTg5OCwiZXhwIjoxNjU1NTk4Mjk4fQ.wC95-bEcm78uOkIVXmOxD6gakSRl8U-F0xrnwiOdWpo

###
### agendamento getOne
GET  http://localhost:3000/api/agendamento/62ad1bd5b76d9082843e100f
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYWQxYThlNzJlN2M5MTY3MWM5ZGZjNyIsImlhdCI6MTY1NTUxMTg5OCwiZXhwIjoxNjU1NTk4Mjk4fQ.wC95-bEcm78uOkIVXmOxD6gakSRl8U-F0xrnwiOdWpo

###
### agendamento post
POST http://localhost:3000/api/agendamento
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYWQxYThlNzJlN2M5MTY3MWM5ZGZjNyIsImlhdCI6MTY1NTUxMTg5OCwiZXhwIjoxNjU1NTk4Mjk4fQ.wC95-bEcm78uOkIVXmOxD6gakSRl8U-F0xrnwiOdWpo
Content-Type: application/json

{
    "title": "Ana",
    "startTime": "Sat Jan 01 2022 07:00:00 GMT-0300 (Hora padrão de Brasília)",
    "endTime": "Sat Jan 01 2022 08:00:00 GMT-0300 (Hora padrão de Brasília)"
}
###
### agendamento put
PUT http://localhost:3000/api/agendamento/6329b8cac2aa11725e22c2a4
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYWQxYThlNzJlN2M5MTY3MWM5ZGZjNyIsImlhdCI6MTY1NTUxMTg5OCwiZXhwIjoxNjU1NTk4Mjk4fQ.wC95-bEcm78uOkIVXmOxD6gakSRl8U-F0xrnwiOdWpo
Content-Type: application/json

{
    "title": "Ana",
    "startTime": "Sat Jan 10 2022 07:00:00 GMT-0300 (Hora padrão de Brasília)",
    "endTime": "Sat Jan 10 2022 08:00:00 GMT-0300 (Hora padrão de Brasília)"
}
###
### agendamento delete
DELETE http://localhost:3000/api/agendamento/6328dc3846e91be6d4aaaf4a
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYWQxYThlNzJlN2M5MTY3MWM5ZGZjNyIsImlhdCI6MTY1NTUxMTg5OCwiZXhwIjoxNjU1NTk4Mjk4fQ.wC95-bEcm78uOkIVXmOxD6gakSRl8U-F0xrnwiOdWpo
###