### 
GET http://localhost:3000/api/project
###
###
GET http://localhost:3000/api/project/632e077cbb7947ff446a2709
###
###
POST http://localhost:3000/api/cash 
Content-Type: application/json

{
    "_id": "6334ab53981b14a6d5babab3",
    "sessions": "10",
    "value": "10",
    "pay": "dinheiro",    
    "total": "100"
}
###
### 
POST http://localhost:3000/api/project
Content-Type: application/json

{
    "userName"      : "Anderson",
    "userLastName"  : " Carvalho Giusti",
    "userBirth"     : "26/12/1989",
    "userPhone"     : "11 99249-9734",
    "userEmail"     : "tetsadooo@hotmail.com",
    "userCpf"       : "37593539830",
    "userAddress"   : "Avenida Odair Santanelli",
    "userNumber"    : "990",
    "userComplement": "Bloco 15 Apto B14",
    "userCity"      : "Guarulhos",
    "userState"     : "SP",
    "userPermission": "paciente",
    "tasks": [
        {
            "title": "array 1"
        }
    ]
}

###
### 
PUT http://localhost:3000/api/project/632e0c0c6e10219da354bc4c
Content-Type: application/json

{
    "title": "TESTE 1",
    "description": "TESTANDO RELACINAMENTO",
    "tasks": [
        {
            "title": "array 1"
        }
    ]
}

###
### 
GET http://localhost:3000/api/user
###
### 
GET http://localhost:3000/api/userPacient
###
### 
GET http://localhost:3000/api/user/633369cbcf115379f8eba9ef
###
### 
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "userName"      : "Teste 10000",
    "userLastName"  : " Carvalho Giusti",
    "userBirth"     : "26/12/1989",
    "userPhone"     : "11 99249-9734",
    "userEmail"     : "100000@hotmail.com",
    "userCpf"       : "37593539830",
    "userAddress"   : "Avenida Odair Santanelli",
    "userNumber"    : "990",
    "userComplement": "Bloco 15 Apto B14",
    "userCity"      : "Guarulhos",
    "userState"     : "SP",
    "userPermission": "paciente",
    "prontuarios": [
        {
            "treatment": "aaaaaa"
        }
    ]
}
   
###
### 
PUT http://localhost:3000/api/user/63344ecc8d3a206530c69d8e
Content-Type: application/json

{    
    "prontuarios": [
        {
            "treatment": "aaaaaaaaaaaaa"
        }
    ]
}
###
### 
DELETE http://localhost:3000/api/user/629e970dbe638658a42f7533
###
### 
DELETE http://localhost:3000/api/project/632e0623c444ecd0d93cd867
###
### 
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "userName"      : "Anderson 2",
    "userLastName"  : " Carvalho Giusti",
    "userBirth"     : "26/12/1989",
    "userPhone"     : "11 99249-9734",
    "userEmail"     : "2@hotmail.com",
    "userCpf"       : "37593539830",
    "userAddress"   : "Avenida Odair Santanelli",
    "userNumber"    : "990",
    "userComplement": "Bloco 15 Apto B14",
    "userCity"      : "Guarulhos",
    "userState"     : "SP",
    "userPermission": "paciente"
}
   
###
### 
PUT http://localhost:3000/api/userChart/6334ab53981b14a6d5babab3
Content-Type: application/json

{    
    "treatment": "delete Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam venenatis, leo ut scelerisque mattis, risus mauris vestibulum tellus, eget convallis felis purus ac lectus. Aliquam aliquam posuere elit non tincidunt. Nam accumsan nulla sed dui auctor, ut porttitor ex convallis. Suspendisse vehicula hendrerit orci. Morbi sodales eu libero interdum aliquet. Aenean mi est, vulputate nec efficitur ac, lacinia venenatis tellus. Cras sed libero eu felis rutrum hendrerit. Nulla scelerisque quis enim sollicitudin facilisis. Proin sed urna nec dolor ornare congue porttitor bibendum felis. Morbi eget libero a elit ullamcorper congue. Aliquam placerat vestibulum nibh, id luctus felis porttitor quis."
}
###
### 
GET http://localhost:3000/api/userPacient
###
### prontuario getAll
GET http://localhost:3000/api/prontuario
Content-Type: application/json

{    
    "user": "6334ab53981b14a6d5babab3",
    "treatment": "delete Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam venenatis, leo ut scelerisque mattis, risus mauris vestibulum tellus, eget convallis felis purus ac lectus. Aliquam aliquam posuere elit non tincidunt. Nam accumsan nulla sed dui auctor, ut porttitor ex convallis. Suspendisse vehicula hendrerit orci. Morbi sodales eu libero interdum aliquet. Aenean mi est, vulputate nec efficitur ac, lacinia venenatis tellus. Cras sed libero eu felis rutrum hendrerit. Nulla scelerisque quis enim sollicitudin facilisis. Proin sed urna nec dolor ornare congue porttitor bibendum felis. Morbi eget libero a elit ullamcorper congue. Aliquam placerat vestibulum nibh, id luctus felis porttitor quis."

}
### prontuario 
GET http://localhost:3000/api/prontuario/6334ab53981b14a6d5babab3
###
POST http://localhost:3000/api/cash 
Content-Type: application/json

{
    "sessions": "100",
    "value": "100",
    "pay": "debito",    
    "total": "1000",
    "user": "6334ab53981b14a6d5babab3"
}
###
###
GET http://localhost:3000/api/cash
###
###
DELETE http://localhost:3000/api/cash/6342e380c3c514e93c49f1e7
###